import type { ScoreRow } from "@/lib/features/scoring/types";
import { CALENDAR } from "@/lib/features/scoring/windows";

/** Fila de score sana y completa; los tests sobrescriben solo lo que miden. Solo tests. */
export function scoreRowFixture(partial: Partial<ScoreRow> = {}): ScoreRow {
  return {
    company: "c",
    month: CALENDAR[0],
    groupId: "g",
    versionParametros: "v",
    score: 80,
    scoreSolo: 80,
    avalGrupo: 0,
    confianza: 0.9,
    subscores: { A: 80, B: 80, C: 80 },
    confs: { A: 1, B: 1, C: 1 },
    estado: "sana",
    variables: [],
    deltaContrib: [],
    direccion: "estable",
    naturaleza: "sin_cambio",
    tendScore3m: null,
    tend3m: { A: null, B: null, C: null },
    rachaB2: 0,
    rachaDeficit: 0,
    C3dias: null,
    C4: null,
    cobrosOpMedia3m: 100_000,
    cobrosOpMedia6m: 100_000,
    pagosOpMedia6m: 60_000,
    servicioDeudaMedia6m: 5_000,
    amortCreditoMedia6m: 0,
    obligacionesRecMedia6m: 0,
    capacidadCuotaAdv: 0,
    D1: 1,
    D2: null,
    D3: null,
    D4: null,
    D5: 0,
    confD: 0,
    tienePrestamoIntragrupo: false,
    cobrosOpGrupoMedia6m: 0,
    pagosOpGrupoMedia6m: 0,
    servicioDeudaGrupoMedia6m: 0,
    scoreGrupo: null,
    deficitMes: false,
    margenMes: 0.15,
    senales: {
      deterioro: false,
      estructural: false,
      mejora: false,
      deficit: false,
      impago: false,
      vencidoAlto: false,
      contagio: false,
      datosInsuficientes: false,
    },
    alertas: [],
    cobertura: {
      mesesObs6m: 6,
      mesesObs12m: 6,
      pctClasificado6m: 1,
      nFacturasCli6m: 0,
      nFacturasProv6m: 0,
      tieneLineaCredito: false,
      tieneCuotas: true,
      C4Estimado: true,
      importesExcluidosEur: 0,
      nHermanasConDatos: 0,
    },
    ...partial,
  };
}
