import type { ScoreRow } from "@/lib/features/scoring/types";
import { PARAMS, VARIABLES } from "@/lib/features/scoring/params";
import { CALENDAR } from "@/lib/features/scoring/windows";

/** Fila de score sana y completa; los tests sobrescriben solo lo que miden. Solo tests. */
export function scoreRowFixture(partial: Partial<ScoreRow> = {}): ScoreRow {
  const variables = VARIABLES.map((id) => ({
    id,
    raw: null,
    subnota: 80,
    conf: 1,
    peso: PARAMS.pesosVariables[id],
    pesoEfectivo: PARAMS.pesosVariables[id],
    aportacion: PARAMS.pesosVariables[id] * 80,
    umbralSano: null,
    sano: null,
    aplicable: true,
  }));
  return {
    company: "c",
    month: CALENDAR[0],
    groupId: "g",
    versionParametros: "v",
    scoreSolo: 80,
    ajusteHolding: 0,
    aportacionGrupo: 0,
    deltaGrupo: 0,
    confianza: 0.9,
    subscores: { A: 80, B: 80, C: 80 },
    confs: { A: 1, B: 1, C: 1 },
    estadoSolo: "sana",
    estadoGrupo: "sana",
    perfilGrupo: "estandar",
    variables,
    deltaContrib: VARIABLES.map((id) => ({ id, delta: 0 })),
    direccion: "estable",
    naturaleza: "sin_cambio",
    patronTrayectoria: "estable",
    tendScore3m: null,
    tendScore6m: null,
    tendScore12m: null,
    tend3m: { A: null, B: null, C: null },
    alertaTempranaDeterioro: false,
    evaluacionEwi: {
      revisionStage2Candidata: false,
      ewis: {
        ewi1ImpagoObligaciones: false,
        ewi2MorosidadComercial: false,
        ewi3TensionCobertura: false,
        ewi4DeficitPersistente: false,
      },
    },
    gapCicloDias: null,
    recomendacionEmbat: null,
    requiereAvalMatriz: false,
    alertaPignoracionCaja: false,
    factorDeterminante: { id: "sin_datos", delta: 0, descripcion: "" },
    factorDeterminanteGrupo: { id: "holding", delta: 0, descripcion: "" },
    canarioEnMina: { detectado: false, id: null, mensaje: null },
    diagnosticoMejora: { confirmada: false, motor: null },
    inflexion: {
      hayInflexion: false,
      tipo: "sin_inflexion",
      mesInflexion: null,
      antelacionMeses: 0,
      scoreInflexion: null,
      canalDesencadenante: "ninguno",
      variableDetonante: null,
      explicacion: "",
    },
    inflexionGrupo: {
      hayInflexion: false,
      tipo: "sin_inflexion",
      mesInflexion: null,
      antelacionMeses: 0,
      scoreInflexion: null,
      canalDesencadenante: "ninguno",
      variableDetonante: null,
      explicacion: "",
    },
    rachaB2: 0,
    rachaDeficit: 0,
    C3dias: null,
    C4: null,
    cobrosOpMedia3m: 100_000,
    cobrosOpMedia6m: 100_000,
    pagosOpMedia6m: 60_000,
    servicioDeudaMedia6m: 5_000,
    amortCreditoMedia6m: 0,
    obligacionesRecMedia6m: 0,
    // Coherente con los flujos de arriba: max(0, (0,8·100 000 − 1,1·60 000)/1,3 − 5 000) ≈ 5 769,23.
    capacidadCuotaAdv: 5_769,
    D1: 1,
    D2: null,
    D3: null,
    D4: null,
    D5: 0,
    confD: 0,
    tienePrestamoIntragrupo: false,
    cobrosOpGrupoMedia6m: 0,
    pagosOpGrupoMedia6m: 0,
    servicioDeudaGrupoMedia6m: 0,
    scoreGrupo: 80,
    deficitMes: false,
    margenMes: 0.15,
    senales: {
      deterioro: false,
      estructural: false,
      mejora: false,
      deficit: false,
      impago: false,
      vencidoAlto: false,
      contagio: false,
      datosInsuficientes: false,
      alertaTempranaDeterioro: false,
    },
    alertas: [],
    cobertura: {
      mesesObs6m: 6,
      mesesObs12m: 6,
      pctClasificado6m: 1,
      nFacturasCli6m: 0,
      nFacturasProv6m: 0,
      tieneLineaCredito: false,
      tieneCuotas: true,
      C4Estimado: true,
      importesExcluidosEur: 0,
      nHermanasConDatos: 0,
      hardcoreRevolving: false,
    },
    ...partial,
  };
}
