// Generated by scripts/gen-company-seed.mjs from dataset/companies.csv.
// Real anonymised metadata for a representative slice of the portfolio. Only the
// scores built on top of it in fixtures.ts are synthetic.

export type CompanySeed = {
  id: string;
  groupId: string;
  country: string;
  currency: string;
  erp: string;
};

export const COMPANY_SEED: CompanySeed[] = [
  { id: "COMP_0110", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0464", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0514", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0580", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0643", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0787", groupId: "GROUP_0008", country: "", currency: "EUR", erp: "businessCentral" },
  { id: "COMP_0146", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0374", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0386", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0520", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0717", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_1270", groupId: "GROUP_0020", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0072", groupId: "GROUP_0003", country: "", currency: "GBP", erp: "businessOne" },
  { id: "COMP_0154", groupId: "GROUP_0003", country: "", currency: "GBP", erp: "businessOne" },
  { id: "COMP_0208", groupId: "GROUP_0003", country: "", currency: "GBP", erp: "businessOne" },
  { id: "COMP_0426", groupId: "GROUP_0003", country: "", currency: "EUR", erp: "businessOne" },
  { id: "COMP_0475", groupId: "GROUP_0015", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0545", groupId: "GROUP_0015", country: "", currency: "EUR", erp: "sage50" },
  { id: "COMP_0808", groupId: "GROUP_0015", country: "ES", currency: "EUR", erp: "sage200" },
  { id: "COMP_1210", groupId: "GROUP_0015", country: "", currency: "EUR", erp: "sage200" },
  { id: "COMP_0158", groupId: "GROUP_0001", country: "", currency: "USD", erp: "" },
  { id: "COMP_0853", groupId: "GROUP_0001", country: "", currency: "JPY", erp: "" },
  { id: "COMP_0939", groupId: "GROUP_0001", country: "", currency: "GBP", erp: "" },
  { id: "COMP_0524", groupId: "GROUP_0006", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0855", groupId: "GROUP_0006", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0957", groupId: "GROUP_0006", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0585", groupId: "GROUP_0004", country: "ES", currency: "EUR", erp: "netsuite" },
  { id: "COMP_1188", groupId: "GROUP_0004", country: "ES", currency: "EUR", erp: "netsuite" },
  { id: "COMP_0255", groupId: "GROUP_0025", country: "", currency: "EUR", erp: "dynamicsAx" },
  { id: "COMP_1049", groupId: "GROUP_0025", country: "", currency: "EUR", erp: "dynamicsAx" },
  { id: "COMP_1053", groupId: "GROUP_0002", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0841", groupId: "GROUP_0005", country: "ES", currency: "EUR", erp: "" },
  { id: "COMP_0691", groupId: "GROUP_0010", country: "", currency: "EUR", erp: "datev" },
  { id: "COMP_1042", groupId: "GROUP_0012", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0832", groupId: "GROUP_0014", country: "ES", currency: "EUR", erp: "holded" },
  { id: "COMP_1129", groupId: "GROUP_0024", country: "", currency: "EUR", erp: "" },
  { id: "COMP_1268", groupId: "GROUP_0027", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0235", groupId: "GROUP_0028", country: "", currency: "EUR", erp: "" },
  { id: "COMP_0597", groupId: "GROUP_0029", country: "ES", currency: "EUR", erp: "ekon" },
  { id: "COMP_1286", groupId: "GROUP_0030", country: "", currency: "EUR", erp: "" },
  { id: "COMP_1070", groupId: "GROUP_0031", country: "", currency: "EUR", erp: "sage200" },
  { id: "COMP_0406", groupId: "GROUP_0034", country: "", currency: "EUR", erp: "netsuite" },
  { id: "COMP_0357", groupId: "GROUP_0036", country: "", currency: "EUR", erp: "businessOne" },
  { id: "COMP_0825", groupId: "GROUP_0043", country: "ES", currency: "EUR", erp: "" },
];
